### ISSUE TITLE
Problems with moveit setup

### ISSUE THREAD

**Issue by moucrob** [ros-planning/moveit#1072]
### Description
3 issues when installing...

### Your environment
* ROS Distro: [Kinetic]
* OS Version: e.g. Ubuntu 16.04

### Steps to reproduce
1) Hello, when following this http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/getting_started/getting_started.html, after running : 
`rosdep install -y --from-paths . --ignore-src --rosdistro kinetic`
I get 
`E: Unable to locate package ros-kinetic-joy
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-kinetic-joy] failed
`
2) Then, when catkin building, I got : 
```
Errors     << moveit_tutorials:cmake /home/exs/ws_moveitDebug/logs/moveit_tutorials/build.cmake.001.log
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by
  "moveit_visual_tools" with any of the following names:

    moveit_visual_toolsConfig.cmake
    moveit_visual_tools-config.cmake

  Add the installation prefix of "moveit_visual_tools" to CMAKE_PREFIX_PATH
  or set "moveit_visual_tools_DIR" to a directory containing one of the above
  files.  If "moveit_visual_tools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:13 (find_package)


CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "moveit_visual_tools" with any of the following names:

    moveit_visual_toolsConfig.cmake
    moveit_visual_tools-config.cmake

  Add the installation prefix of "moveit_visual_tools" to CMAKE_PREFIX_PATH
  or set "moveit_visual_tools_DIR" to a directory containing one of the above
  files.  If "moveit_visual_tools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:13 (find_package)
```
3) After : 
`source ~/ws_moveitDebug/devel/setup.bash` and then 
`roslaunch panda_moveit_config demo.launch db:=true`, I get
```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 749, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 721, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 685, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 627, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 665, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 257, in _param_tag
    vals = self.opt_attrs(tag, context, ('value', 'textfile', 'binfile', 'command'))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 202, in opt_attrs
    return [self.resolve_args(tag_value(tag,a), context) for a in attrs]
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: franka_description
```
4) Finally, when `git clone https://github.com/ros-planning/moveit/tree/kinetic-devel/moveit_ros/benchmarks`, I get : 
```
fatal: repository 'https://github.com/ros-planning/moveit/tree/kinetic-devel/moveit_ros/benchmarks/' not found
```

What to do please? Regards

**Comment by BryceStevenWilley** [comment]
Hey @moucrob, this sort of question is best suited for [ROS Answers](https://answers.ros.org/questions/). In general, setup, debugging questions, and things that aren't bugs in MoveIt itself should be posted there. With regards to your problems:

1. This suggests something is strange with your ROS install. The only [similar issue](https://answers.ros.org/question/267169/unable-to-locate-package-ros-kinetic-/) that I could find suggests that you might have a non-standard architecture that `ros-kinetic-joy` isn't built for, or something may be off with you system configuration.

2. If the `rosdep` command didn't finish running, it probably didn't install `moveit_visual_tools`, which is listed as a dependency of the tutorial code along with `joy`. Try this again once you fix the above problem.

3. This is the same problem as above: if `rosdep` never finished running, then `franka_description`, a dependency of `panda_moveit_config`, was never installed, so it can't be found.

4. You are trying to clone a sub-directory of the entire repository, which is not allowed in git. I'm not sure why you want to clone just that sub-directory, but you'll have to clone the whole repository (`git clone https://github.com/ros-planning/moveit`). 

You should open a ROS answers question with more details about the computer you are running this on and focus on solving 1.
