### ISSUE TITLE
Failed to import pyassimp.

### ISSUE THREAD

**Issue by addy1997** [ros-planning/moveit#1670]
I am using **Ubuntu 16.0.4** with **ROS kinetic**.  I got this error while running my code for Collision detection.

 import moveit_commander
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vol/sandbox/ros/install/lib/python2.7/dist-packages/moveit_commander/__init__.py", line 3, in <module>
    from planning_scene_interface import *
  File "/vol/sandbox/ros/install/lib/python2.7/dist-packages/moveit_commander/planning_scene_interface.py", line 48, in <module>
    import pyassimp
  File "/usr/lib/python2.7/dist-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import 

Failed to import pyassimp.

Please help me with this.

**Comment by jschleicher** [comment]
Looks like https://github.com/ros-planning/moveit/issues/1546, which was only present in the testing version 0.9.16. Which version are you using? `apt` packages or source build? Please install all the dependencies, if you build from source please follow the steps in the [tutorial](http://docs.ros.org/melodic/api/moveit_tutorials/html/doc/getting_started/getting_started.html#build-your-catkin-workspace).

**Comment by addy1997** [comment]
I am using 0.9.16  version. Also I have installed moveit by building it
from source.

**Comment by jschleicher** [comment]
Please upgrade to 0.9.17 (fixed) and install the dependency via rosdep.

**Comment by addy1997** [comment]
sure
