### ISSUE TITLE
heap-buffer-overflow in moveit::core::RevoluteJointModel::~RevoluteJointModel

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2068]
Found using this PR: https://github.com/ros-planning/moveit/pull/2057

Debug output from travis run:
```c++
==8541==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x614000006238 at pc 0x7f4a6fef00df bp 0x7ffd06d5e660 sp 0x7ffd06d5e650
READ of size 8 at 0x614000006238 thread T0
    #0 0x7f4a6fef00de in moveit::core::RevoluteJointModel::~RevoluteJointModel() (/root/ros_ws/install/lib/libmoveit_robot_model.so.1.0.1+0xc20de)
    #1 0x7f4a6ff08062 in moveit::core::RobotModel::~RobotModel() (/root/ros_ws/install/lib/libmoveit_robot_model.so.1.0.1+0xda062)
    #2 0x562e08274da5 in std::_Sp_counted_ptr<moveit::core::RobotModel*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (/root/ros_ws/devel/.private/moveit_planners_ompl/lib/moveit_planners_ompl/test_state_space+0x16da5)
    #3 0x562e08277a55 in LoadPlanningModelsPr2_StateSpace_Test::~LoadPlanningModelsPr2_StateSpace_Test() (/root/ros_ws/devel/.private/moveit_planners_ompl/lib/moveit_planners_ompl/test_state_space+0x19a55)
    #4 0x7f4a70ee131e in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/root/ros_ws/build/moveit_planners_ompl/gtest/googlemock/gtest/libgtest.so+0xa031e)
    #5 0x7f4a70ea8d41 in testing::TestInfo::Run() (/root/ros_ws/build/moveit_planners_ompl/gtest/googlemock/gtest/libgtest.so+0x67d41)
    #6 0x7f4a70ea9494 in testing::TestCase::Run() (/root/ros_ws/build/moveit_planners_ompl/gtest/googlemock/gtest/libgtest.so+0x68494)
    #7 0x7f4a70eade05 in testing::internal::UnitTestImpl::RunAllTests() (/root/ros_ws/build/moveit_planners_ompl/gtest/googlemock/gtest/libgtest.so+0x6ce05)
    #8 0x7f4a70eae3f7 in testing::UnitTest::Run() (/root/ros_ws/build/moveit_planners_ompl/gtest/googlemock/gtest/libgtest.so+0x6d3f7)
    #9 0x562e082680ee in main (/root/ros_ws/devel/.private/moveit_planners_ompl/lib/moveit_planners_ompl/test_state_space+0xa0ee)
    #10 0x7f4a6e3f8b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #11 0x562e08268a69 in _start (/root/ros_ws/devel/.private/moveit_planners_ompl/lib/moveit_planners_ompl/test_state_space+0xaa69)
0x614000006238 is located 8 bytes to the left of 432-byte region [0x614000006240,0x6140000063f0)
allocated by thread T0 here:
    #0 0x7f4a711edb40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x7f4a703b2818 in Eigen::internal::aligned_malloc(unsigned long) (/opt/ros/melodic/lib/libompl.so.15+0x216818)
    #2 0xfffa0dab395  (<unknown module>)
SUMMARY: AddressSanitizer: heap-buffer-overflow (/root/ros_ws/install/lib/libmoveit_robot_model.so.1.0.1+0xc20de) in moveit::core::RevoluteJointModel::~RevoluteJointModel()
Shadow bytes around the buggy address:
  0x0c287fff8bf0: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa
  0x0c287fff8c00: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c287fff8c10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c287fff8c20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c287fff8c30: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa
=>0x0c287fff8c40: fa fa fa fa fa fa fa[fa]00 00 00 00 00 00 00 00
  0x0c287fff8c50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c287fff8c60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c287fff8c70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa
  0x0c287fff8c80: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c287fff8c90: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==8541==ABORTING
Cannot find results, writing failure results to '/root/ros_ws/build/moveit_planners_ompl/test_results/moveit_planners_ompl/MISSING-gtest-test_state_space.xml'
```

**Comment by jliukkonen** [comment]
I’ll work on this for WMD 2020. I'll see what problems ASAN points out if I enable it locally.
