### ISSUE TITLE
memory leak in libmoveit_move_group_default_capabilities

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2074]
Found using this PR: #2057

Debug output from travis run:

```C++
Indirect leak of 36 byte(s) in 1 object(s) allocated from:
    #0 0x7f513a949532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f511bb62f30 in void class_loader::class_loader_private::registerPlugin<move_group::MoveGroupGetPlanningSceneService, move_group::MoveGroupCapability>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/root/ros_ws/install/lib/libmoveit_move_group_default_capabilities.so+0x1bdf30)
    #2 0x7f511ba34207 in _GLOBAL__sub_I_get_planning_scene_service_capability.cpp (/root/ros_ws/install/lib/libmoveit_move_group_default_capabilities.so+0x8f207)
    #3 0x7f511bb877c7  (/root/ros_ws/install/lib/libmoveit_move_group_default_capabilities.so+0x1e27c7)
Indirect leak of 36 byte(s) in 1 object(s) allocated from:
    #0 0x7f513a949532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f511bb63962 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.137] (/root/ros_ws/install/lib/libmoveit_move_group_default_capabilities.so+0x1be962)
```

**Comment by tylerjw** [comment]
duplicate
