### ISSUE TITLE
Moveit! Benchmarking Tutorial: Can't plot a PDF file.

### ISSUE THREAD

**Issue by VitaminLL** [ros-planning/moveit#2258]
### Description

I am able to generate pdf plots for moveit benchmarking, but the PDF can't open.

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04
* Source 
* kinetic-devel

### Steps to reproduce
I follow the benchmarking tutorial(http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/benchmarking/benchmarking_tutorial.html). 
I ran moveit benchmarking and processed the log with,

**rosrun moveit_ros_benchmarks moveit_benchmark_statistics.py -p xx.pdf /home/sl2769-2020/York/all_planner_db/Library_Table_O_S/LibraryTable_Start1_Table_sl27692020-Linux_2020-08-12T10:49:44.908796.log** 

and I got the error as the actual behaviour is shown.

### Actual behaviour

Processing /home/sl2769-2020/York/all_planner_db/Library_Table_O_S/LibraryTable_Start1_Table_sl27692020-Linux_2020-08-12T10:49:44.908796.log
Parsing data for RRTkConfigDefault (ompl)
Parsing data for RRTConnectkConfigDefault (ompl)
Parsing data for PRMkConfigDefault (ompl)
Parsing data for PRMstarkConfigDefault (ompl)
Generating plots...
/usr/lib/python2.7/dist-packages/matplotlib/cbook.py:2038: RuntimeWarning: overflow encountered in double_scalars
  loval = q1 - whis * stats['iqr']
/usr/lib/python2.7/dist-packages/matplotlib/cbook.py:2039: RuntimeWarning: overflow encountered in double_scalars
  hival = q3 + whis * stats['iqr']
/usr/lib/python2.7/dist-packages/matplotlib/transforms.py:2770: RuntimeWarning: overflow encountered in double_scalars
  vmax += expander*abs(vmax)
/usr/lib/python2.7/dist-packages/matplotlib/ticker.py:1424: RuntimeWarning: invalid value encountered in double_scalars
  extra_bins = int(divmod((best_vmax - vmax), step)[0])
Traceback (most recent call last):
  File "/home/sl2769-2020/ws_moveit/src/moveit/moveit_ros/benchmarks/scripts/moveit_benchmark_statistics.py", line 601, in <module>
    plotStatistics(options.dbname, options.plot)
  File "/home/sl2769-2020/ws_moveit/src/moveit/moveit_ros/benchmarks/scripts/moveit_benchmark_statistics.py", line 460, in plotStatistics
    plotAttribute(c, planners, col[1], col[2])
  File "/home/sl2769-2020/ws_moveit/src/moveit/moveit_ros/benchmarks/scripts/moveit_benchmark_statistics.py", line 369, in plotAttribute
    plt.boxplot(measurements, notch=0, sym='k+', vert=1, whis=1.5, bootstrap=1000)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 2710, in boxplot
    manage_xticks=manage_xticks, data=data)
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1814, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 3323, in boxplot
    manage_xticks=manage_xticks)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 3652, in bxp
    boxes.extend(doplot(box_x, box_y, **final_boxprops))
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 3566, in doplot
    return self.plot(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1814, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 1428, in plot
    self.autoscale_view(scalex=scalex, scaley=scaley)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 2197, in autoscale_view
    y0, y1 = ylocator.view_limits(y0, y1)
  File "/usr/lib/python2.7/dist-packages/matplotlib/ticker.py", line 1452, in view_limits
    return np.take(self.bin_boundaries(dmin, dmax), [0, -1])
  File "/usr/lib/python2.7/dist-packages/matplotlib/ticker.py", line 1424, in bin_boundaries
    extra_bins = int(divmod((best_vmax - vmax), step)[0])
ValueError: cannot convert float NaN to integer

and I will get a pdf document(xx.pdf). When I open xx.pdf, it's shown: 
![error](https://user-images.githubusercontent.com/27075545/90247091-c3e9de80-de2d-11ea-92a2-50022f56d0c4.png)

How do I successfully generate pdf plot?

**Comment by felixvd** [comment]
I haven't used `moveit_benchmarks`, but the error `ValueError: cannot convert float NaN to integer` looks like there might be something wrong with your data. Maybe have a look if it looks good, or if something went wrong during the generation?
