### ISSUE TITLE
OCTOMAP doesn't let Rviz plugin connect to move_group node

### ISSUE THREAD

**Issue by rishabh900** [ros-planning/moveit#2503]
### Description

I have build MoveIt and the my moveit package in catkin. When i am launching my robot model in gazebo including the kinect camera and in Rviz via separate launch according to the MoveIt's melodic branch tutorial the Octomap isn't just letting the move_group node/action server to connect. 

### Your environment
* ROS Distro: [|Melodic]
* OS Version: Ubuntu 18.04
* Moveit build from source , melodic-devel

### Backtrace or Console output
```
You can start planning now!

process[rviz_punch_12891_6579944060169940171-2]: started with pid [12907]
[ INFO] [/tmp/binarydeb/ros-melodic-rviz-1.13.15/src/rviz/visualizer_app.cpp]:[114] : rviz version 1.13.15
[ INFO] [/tmp/binarydeb/ros-melodic-rviz-1.13.15/src/rviz/visualizer_app.cpp]:[115] : compiled against Qt version 5.9.5
[ INFO] [/tmp/binarydeb/ros-melodic-rviz-1.13.15/src/rviz/visualizer_app.cpp]:[117] : compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [/tmp/binarydeb/ros-melodic-rviz-1.13.15/src/rviz/ogre_helpers/render_system.cpp]:[85] : Forcing OpenGl version 0.
[ INFO] [/tmp/binarydeb/ros-melodic-rviz-1.13.15/src/rviz/ogre_helpers/render_system.cpp]:[458] : Stereo is NOT SUPPORTED
[ INFO] [/tmp/binarydeb/ros-melodic-rviz-1.13.15/src/rviz/ogre_helpers/render_system.cpp]:[226] : OpenGl version: 4.6 (GLSL 4.6).
[ INFO] [/home/curse/Ros_Melodic/src/moveit/moveit_core/robot_model/src/robot_model.cpp]:[92] : Loading robot model 'full_assemblage'...


[ INFO] [/home/curse/Ros_Melodic/src/moveit/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp]:[987] : Starting planning scene monitor
[ INFO] [/home/curse/Ros_Melodic/src/moveit/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp]:[993] : Listening to '/move_group/monitored_planning_scene'


move_group: /opt/ros/melodic/include/octomap/OcTreeBaseImpl.hxx:208: const NODE* octomap::OcTreeBaseImpl<NODE, INTERFACE>::getNodeChild(const NODE*, unsigned int) const [with NODE = octomap::OcTreeNode; INTERFACE = octomap::AbstractOccupancyOcTree]: Assertion `(childIdx < 8) && (node->children != NULL)' failed.


[ INFO] [/home/curse/Ros_Melodic/src/moveit/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp]:[505] : Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?

QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)

[ INFO] [/home/curse/Ros_Melodic/src/moveit/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp]:[361] : Constructing new MoveGroup connection for group 'arm_l' in namespace ''
[move_group-1] process has died [pid 12906, exit code -6, cmd /home/curse/Ros_Melodic/devel/lib/moveit_ros_move_group/move_group --debug __name:=move_group __log:=/home/curse/.ros/log/326f06dc-5fed-11eb-b5d5-a909d334d26b/move_group-1.log].
log file: /home/curse/.ros/log/326f06dc-5fed-11eb-b5d5-a909d334d26b/move_group-1*.log


[ERROR] [/home/curse/Ros_Melodic/src/moveit/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp]:[380] : Unable to connect to move_group action server 'move_group' within allotted time (30s)
[ INFO] [/home/curse/Ros_Melodic/src/moveit/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp]:[361] : Constructing new MoveGroup connection for group 'arm_l' in namespace ''
[ERROR] [/home/curse/Ros_Melodic/src/moveit/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp]:[380] : Unable to connect to move_group action server 'move_group' within allotted time (30s)
[ INFO] [/home/curse/Ros_Melodic/src/moveit/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp]:[361] : Constructing new MoveGroup connection for group 'arm_l' in namespace ''
[ERROR] [/home/curse/Ros_Melodic/src/moveit/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp]:[380] : Unable to connect to move_group action server 'move_group' within allotted time (30s)
```
In above console output too you could see the message provided via move_group upon some assertion being fail in Octomap.

It's gdb backtrace came out to be:-

```
Thread 1 "rviz" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00007fff4ba0003f in Ogre::GLSL::GLSLLinkProgram::compileAndLink() ()
    at /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/RenderSystem_GL.so.1.9.0
#2  0x00007fff4ba00e63 in Ogre::GLSL::GLSLLinkProgram::activate() () at /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/RenderSystem_GL.so.1.9.0
#3  0x00007fff4ba03695 in Ogre::GLSL::GLSLLinkProgramManager::getActiveLinkProgram() ()
    at /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/RenderSystem_GL.so.1.9.0
#4  0x00007fff4b9fe5cd in Ogre::GLSL::GLSLGpuProgram::bindProgramParameters(Ogre::SharedPtr<Ogre::GpuProgramParameters>, unsigned short) () at /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/RenderSystem_GL.so.1.9.0
#5  0x00007fff4ba5e050 in Ogre::GLRenderSystem::bindGpuProgramParameters(Ogre::GpuProgramType, Ogre::SharedPtr<Ogre::GpuProgramParameters>, unsigned short) () at /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/RenderSystem_GL.so.1.9.0
#6  0x00007ffff31bbd84 in Ogre::SceneManager::updateGpuProgramParameters(Ogre::Pass const*) ()
    at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#7  0x00007ffff31c8b60 in Ogre::SceneManager::renderSingleObject(Ogre::Renderable*, Ogre::Pass const*, bool, bool, Ogre::HashedVector<Ogre::Light*> const*) () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
---Type <return> to continue, or q <return> to quit---
#8  0x00007ffff316b059 in Ogre::QueuedRenderableCollection::acceptVisitorGrouped(Ogre::QueuedRenderableVisitor*) const ()
    at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#9  0x00007ffff316b164 in Ogre::QueuedRenderableCollection::acceptVisitor(Ogre::QueuedRenderableVisitor*, Ogre::QueuedRenderableCollection::OrganisationMode) const () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#10 0x00007ffff31b51af in Ogre::SceneManager::renderBasicQueueGroupObjects(Ogre::RenderQueueGroup*, Ogre::QueuedRenderableCollection::OrganisationMode) () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#11 0x00007ffff31b502e in Ogre::SceneManager::renderVisibleObjectsDefaultSequence() () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#12 0x00007ffff31cabfb in Ogre::SceneManager::_renderScene(Ogre::Camera*, Ogre::Viewport*, bool) ()
    at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#13 0x00007ffff2fd9d2a in Ogre::Camera::_renderScene(Ogre::Viewport*, bool) () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#14 0x00007ffff318647a in Ogre::RenderTarget::_updateViewport(Ogre::Viewport*, bool) () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#15 0x00007ffff318628b in Ogre::RenderTarget::_updateAutoUpdatedViewports(bool) () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#16 0x00007ffff318600e in Ogre::RenderTarget::updateImpl() () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#17 0x00007ffff3186a34 in Ogre::RenderTarget::update(bool) () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
---Type <return> to continue, or q <return> to quit---
#18 0x00007ffff316f4df in Ogre::RenderSystem::_updateAllRenderTargets(bool) () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#19 0x00007ffff31aca4a in Ogre::Root::_updateAllRenderTargets() () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#20 0x00007ffff31acb30 in Ogre::Root::renderOneFrame() () at /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#21 0x00007ffff7b46c68 in rviz::VisualizationManager::onUpdate() () at /opt/ros/melodic/lib/librviz.so
#22 0x00007ffff6cb5555 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff6cc1fc7 in QTimer::timeout(QTimer::QPrivateSignal) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff6cc2328 in QTimer::timerEvent(QTimerEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff6cb607b in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff729b83c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff72a3104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff6c868d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff6cded2e in QTimerInfoList::activateTimers() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff6cdf529 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff0029417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#32 0x00007ffff0029650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff00296dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff6cdf88f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff6c8490a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff6c8d9b4 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x0000555555554dcf in main ()
```

Kindly help me out.

**Comment by rishabh900** [comment]
Sorry it was my foolishness, I was using "DRI_PRIME=1" as argument to roslaunch my files which itself was not a great thing to do.
