### ISSUE TITLE
Problems show up when trying to plan with control

### ISSUE THREAD

**Issue by canVa4** [ros-planning/moveit#2642]
Hi~ I'm trying to plan for robot with non-holonomic constraints, e.g. a two-wheeled car-like base. To do this, I followed how the `ompl_interface::ModelBasedPlanningContext` works and create a new context for planning with control using OMPL. What I have done was adding an control space and a ODE. Plus , I am still using the original state space that is `ompl_interface::ModelBasedStateSpace`. But in my implementation, this problem shows up
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >' what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
``` 
I find that the current planner I used(RRT) can correctly sample state and construct the tree for some small amount but then it will crush. I have no idea why this problem shows up. For now, I using a StateValidChecker that always return true for testing what is wrong.
The following is the gdb debug results.
```
(gdb) bt
#0  0x00007ffff56d8438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff56da03a in __GI_abort () at abort.c:89
#2  0x00007ffff5d1284d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5d106b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5d10701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5d3bd38 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff62116ba in start_thread (arg=0x7fffaf7fe700) at pthread_create.c:333
#7  0x00007ffff57aa4dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by tylerjw** [comment]
@mamoll
