### ISSUE TITLE
moveit_task_constructor_msgs breaks compilation

### ISSUE THREAD

**Issue by icosac** [ros-planning/moveit#3498]
### Description

Compiling new installation. I followed the [getting started](https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html) guide and when I reach the point to compile using `colcon build --mixin release`, the compilation stops when it gets to moveit_task_constructor_msgs.

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* Source or Binary build? Source 
* If source, which branch? Release

### Steps to reproduce

Follow the getting started guide until section "Build your Colcon Workspace".

### Expected behaviour

The compilation should complete without errors.

### Actual behaviour

The compilation stops when compiling moveit_task_constructor_msgs throwing a TypeError. 

### Backtrace or Console output

```
moveit_task_constructor_msgsFinished <<< moveit_msgs [1.61s]
Starting >>> moveit_core
Starting >>> moveit_task_constructor_msgs
Finished <<< moveit_task_constructor_msgs [0.98s]
--- stderr: moveit_core
Traceback (most recent call last):
  File "/opt/ros/humble/bin/generate_parameter_library_cpp", line 33, in <module>
    sys.exit(load_entry_point('generate-parameter-library-py==0.3.6', 'console_scripts', 'generate_parameter_library_cpp')())
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/generate_cpp_header.py", line 66, in main
    run(output_file, yaml_file, validate_header)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/generate_cpp_header.py", line 45, in run
    gen_param_struct.parse(yaml_file, validate_header)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 733, in parse
    self.parse_dict(self.namespace, doc[self.namespace], [])
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 831, in parse_dict
    self.parse_dict(key, root_map[key], nested_name)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 837, in parse_dict
    self.parse_params(name, root_map, nested_name)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 741, in parse_params
    ) = preprocess_inputs(self.language, name, value, nested_name_list)
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 658, in preprocess_inputs
    code_gen_variable = CodeGenVariable(
  File "/opt/ros/humble/lib/python3.10/site-packages/generate_parameter_library_py/parse_yaml.py", line 144, in __init__
    def __init__(
  File "/home/enrico/.local/lib/python3.10/site-packages/typeguard/_functions.py", line 113, in check_argument_types
    check_type_internal(value, expected_type, memo=memo)
  File "/home/enrico/.local/lib/python3.10/site-packages/typeguard/_checkers.py", line 679, in check_type_internal
    if not isinstance(value, origin_type):
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
gmake[2]: *** [online_signal_smoothing/CMakeFiles/moveit_butterworth_parameters.dir/build.make:71: online_signal_smoothing/moveit_butterworth_parameters/include/moveit_butterworth_parameters.hpp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1768: online_signal_smoothing/CMakeFiles/moveit_butterworth_parameters.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< moveit_core [8.21s, exited with code 2]

Summary: 18 packages finished [10.0s]
  1 package failed: moveit_core
  2 packages had stderr output: moveit_configs_utils moveit_core
  45 packages not processed
```

**Comment by rhaschke** [comment]
The console output refers to an error in `moveit_core` (processing `generate_parameter_library_cpp`).
