### ISSUE TITLE
Error in launching Joystick_contol.launch

### ISSUE THREAD

**Issue by kashyapm94** [ros-planning/moveit#881]
### Description

Hey guys,

I am trying to control my robot arm with a XBOX 360 console, When I am trying to launch the launch file (joystick_control.launch), I am getting the following error below. Can anyone kindly tell me as to where am I committing the mistake? Thanks in advance !

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04

### Steps to reproduce
I launched the demo.launch file of robot arm and then launched the move_group.launch file too from a different terminal. Then, from the third terminal I launched the joystick_control.launch file and then I am getting the following error.

### Backtrace or Console output

```
roslaunch joystick_control.launch 
... logging to /home/kashyap/.ros/log/0e62e4cc-4b94-11e8-91a2-e82a44e7a573/roslaunch-kashyap-Lenovo-ideapad-320-15IKB-21878.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://kashyap-Lenovo-ideapad-320-15IKB:34895/
SUMMARY
========
PARAMETERS
* /joy/autorepeat_rate: 40
* /joy/coalesce_interval: 0.025
* /joy/deadzone: 0.2
* /joy/dev: /dev/input/js0
* /rosdistro: kinetic
* /rosversion: 1.12.13

NODES
/
 joy (joy/joy_node)
moveit_joy (moveit_ros_visualization/moveit_joy.py)
ROS_MASTER_URI=http://localhost:11311

process[joy-1]: started with pid [21895]
process[moveit_joy-2]: started with pid [21896]
[ERROR] [1524996050.168624845]: Couldn't open joystick /dev/input/js0. Will retry every second.
[ INFO] [1524996050.967877063]: Loading robot model 'igus'...
[ INFO] [1524996050.967919483]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1524996051.220354327]: Loading robot model 'igus'...
[ INFO] [1524996051.220388920]: No root/virtual joint specified in SRDF. Assuming fixed joint
[FATAL] [1524996051.417448]: Check if you started movegroups. Exiting.
Traceback (most recent call last):
 File "/home/kashyap/catkin_ws/src/moveit/moveit_ros/visualization/scripts/moveit_joy.py", line 42, in <module>
app = MoveitJoy()
File "/home/kashyap/catkin_ws/src/moveit/moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py", line 381, in __init__
 self.updatePlanningGroup(0)
File "/home/kashyap/catkin_ws/src/moveit/moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py", line 405, in updatePlanningGroup
raise rospy.ROSInitException(msg)
rospy.exceptions.ROSInitException: Check if you started movegroups. Exiting.
[moveit_joy-2] process has died [pid 21896, exit code 1, cmd /home/kashyap/catkin_ws/src/moveit/moveit_ros/visualization/scripts/moveit_joy.py __name:=moveit_joy __log:=/home/kashyap/.ros/log/0e62e4cc-4b94-11e8-91a2-e82a44e7a573/moveit_joy-2.log].
log file: /home/kashyap/.ros/log/0e62e4cc-4b94-11e8-91a2-e82a44e7a573/moveit_joy-2*.log
```

**Comment by Kiwigamer** [comment]
Hey,
did you solve the problem, back in 2018?
If so do you remember how?

**Comment by kashyapm94** [comment]
@Kiwigamer hey, sorry I don’t remember how I solved this problem. I don’t work with ROS anymore

**Comment by Kiwigamer** [comment]
despite that, thank you for the answer
